config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :books
  resources :needed_books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :current_owner, class_name: "User", optional: true

  enum state: [ :borrow, :sell, :exchange ]

  # validates :title
  # validates :author
  # valisates :publication_year, numericality: { only_integer: true }
end

app/models/needed_book.rb
class NeededBook < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :needed_books

  def name
    "#{self.first_name} #{self.last_name}" || ''
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_current_user
  before_action :configure_permitted_parameters, if: :devise_controller?

  def fetch_current_user
    if current_user
      @current_user = current_user
    end
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.current_owner = current_user
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :state, :publication_year, :summary, :image)
  end
end

app/controllers/needed_books_controller.rb
class NeededBooksController < ApplicationController

  def update
    @needed_book = NeededBook.find params[:id]
    if @needed_book.update needed_book_params
      redirect_to user_path(current_user)
    end
  end

  private

  def needed_book_params
    params.require(:needed_book).permit(:title, :author)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @needed_book = @current_user.needed_books.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="row">
  <div class="col-2">
    <div class="sidenav">
        <% if @current_user  %>
      <h2 class="w-100 btn btn-primary text-white">
        <%= link_to 'Add book', new_book_url, class: "text-white" %>
      </h2>
        <% end  %>
      <h2 class="ml-2">Latest books</h2>
      <% Book.order(created_at: :DESC).first(5).each do |book| %>
        <%= link_to "#{book.title}", book_url(book), class: "book-item"%>
      <% end  %>

    </div>
  </div>
  <div class="col-10">
    <div class="container">
      <div class="row">
          <% @books.each do |book| %>
            <div class="col-3 mt-3">
              <div class="card item px-2">
                <% if book.image %>
                  <%= image_tag book.image, class: "card-img-top" %>
                <% end %>
                <div class="card-body">
                  <%= link_to book_url(book) do %>
                    <h5 class="card-title"><%= book.title%></h5>
                  <% end %>
                  <p class="card-text"><%= book.author%></p>
                  <p class="card-text"><%= book.current_owner&.name || ''%></p>
                  <p class="card-text"><%= book.publication_year%></p>
                  <%
                  case book.state
                  when 'sell'
                    badge_class = 'badge-danger'
                  when 'exchange'
                    badge_class = 'badge-success'
                  else
                    badge_class = 'badge-warning'
                  end
                  %>
                  <span class="<%="badge #{badge_class}"%>"><%= book.state %></span>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<%= form_for @book, remote: true do |f| %>

<div class="wrapper">
    <h1 class="main-title text-center">Add book from</h1>
    <div class="container">
      <form class="form-main">
        <h3 class="form-title">Complete form to add book!</h3>
        <div class="form-group row">
          <div class="left-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.label :title %><br>
          </div>
          <div class="right-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.text_field :title, class: "input-text form-control" %>
          </div>

        </div>
        <div class="form-group row">
          <div class="left-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.label :author %><br>
          </div>
          <div class="right-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.text_field :title, class: "input-text form-control", placeholder: "Enter author name" %>
          </div>

        </div>

        <div class="form-group row">
          <div class="left-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.label :image %><br>

          </div>
          <div class="right-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.text_field :image, class: "input-text form-control", placeholder: "Enter image url" %>
          </div>

        </div>

        <div class="form-group row">
          <div class="left-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.label :publication_year %><br>

          </div>
          <div class="right-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.text_field :publication_year, class: "input-text form-control", placeholder: "Enter book year" %>
          </div>

        </div>



        <div class="form-group row">
          <div class="left-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.label :summary %><br>
          </div>
          <div class="right-col col-12 col-sm-12 col-md-6 col-lg-6">
            <%= f.text_field :summary, class: "input-text form-control", placeholder: "Enter image url", placeholder: "Write something about book :)" %>
          </div>

        </div>
        <div class="form-group row">
          <div class="dropdown row">
          <p>
            <%= f.label :state, class: "col-6"%><br>
            <%= f.select :state, ['sell', 'borrow', 'exchange'], class: "dropdown-menu col-6"%>
          </p>
          </div>
        </div>


        <div class="text-center group-btn">
          <%= f.submit %>

        </div>
      </form>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-2 border border-dark" id="left">
      <h4 class="text-center title-mini border border-dark">Category</h4>
      <div class="row">
        <div class="col">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Romance</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Actions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Fantasy</a>
            </li>
          </ul>
        </div>
      </div>
      <h4 class="text-center title-mini border border-dark">Hot</h4>
      <div class="row">
        <div class="col">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Item 1...</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Item 2...</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Item 3...</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Item 4...</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Item 5...</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-10 border border-dark">
      <h4 class="title-center">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to 'Home', books_path %></li>
            <li class="breadcrumb-item active" aria-current="page"><%= link_to "#{@book.title}", book_path(@book) %></li>
          </ol>
        </nav>
      </h4>
      <div class="row product-top">
        <div class="col-6 left">
          <div class="big-image">
            <% if @book.image %>
            <%= image_tag @book.image, class: 'img-fluid' %>
            <% end %>
          </div>
        </div>
        <div class="col-6 right">
          <h2 class="product-title text-capitalize"><%= @book.title%></h2>
          <h4 class="title-author">Author: <i><%= @book.author%></i> </h4>
          <h4 class="one-descrip"><b>Current ownner:</b> <%= @book.current_owner&.name || ''%> </h4>
          <h4 class="one-descrip">
            <b>Status:</b>
            <%
              case @book.state
              when 'sell'
                badge_class = 'badge-danger'
              when 'exchange'
                badge_class = 'badge-success'
              else
                badge_class = 'badge-warning'
              end
            %>
            <span class="<%="badge #{badge_class}"%>"><%= @book.state %></span>
          </h4>
          <h3 class="title-sum">Summary:</h3>
          <p class="summary-content">
            <%= @book.summary%>
          </p>
          <div class="action text-center">
            <button type="button" class="btn btn-success m-auto">Book Now</button>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrumBookExchange</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>repl.it</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="border border-dark navbar navbar-expand-md navbar-light bg-light">
      <%= link_to 'Book Exchange', books_path, class: "navbar-brand text-capitalize brand" %>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link nav-cus" href="#">Categories</a>

          </li>
          <li class="nav-item">
            <a class="nav-link nav-cus" href="#">Contact us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link nav-cus" href="#">Follow us</a>
          </li>

        </ul>
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <% if @current_user %>
          <li class="nav-item mr-3">
            <%= link_to user_path(@current_user) do %>
              <%= @current_user.name %>
            <%end%>
          </li>
          <li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>

          </li>
          <% else %>
          <%= link_to 'Login', new_user_session_path %>
        <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.slim
.container
  .row
    .col-2
    .col-8.sign-up-form.mt-3
      h3 Profile
      hr
      .row
        .col-6.avatar.border-right
          img.img-fluid src="https://i.pinimg.com/originals/57/dc/69/57dc695c383af1aaf38798eaccceb4e5.jpg" alt="avatar"
        .col-6
          form
            .form-row
              .form-group.col-md-12
                label for="inputEmail4" Email
                input#inputEmail4.form-control type="email" placeholder="someone@domain.com" readonly="true" value="#{@current_user.email}"
            .form-row
              .form-group.col-md-6
                label First Name
                input.form-control placeholder="First name" readonly="true" value="#{@current_user.first_name}"
              .form-group.col-md-6
                label Last Name
                input.form-control placeholder="Last name" readonly="true" value="#{@current_user.last_name}"
      hr/
      h3 My needs
      hr/
      .row

        ul.list-group.p-3
          li.list-group-item
            .form-group
              - unless @current_user.needed_books.first.nil?
                label Book 1
                = form_for @current_user.needed_books.first, remote: true do |form|
                  .row
                    .col-5
                      = form.text_field :title, placeholder:"Book title", value:"#{@current_user.needed_books.first.title}", class:"form-control"
                    .col-5
                      = form.text_field :author, placeholder:"Book title", value:"#{@current_user.needed_books.first.author}", class:"form-control"
                    .col-2
                      = form.submit "Edit", class:"btn btn-warning"
              - unless @current_user.needed_books.find_by_id(2).nil?
                label Book 2
                = form_for @current_user.needed_books.find_by_id(2), remote: true do |form|
                  .row
                    .col-5
                      = form.text_field :title, placeholder:"Book title", value:"#{@current_user.needed_books.find(2).title}", class:"form-control"
                    .col-5
                      = form.text_field :author, placeholder:"Book title", value:"#{@current_user.needed_books.find(2).author}", class:"form-control"
                    .col-2
                      = form.submit "Edit", class:"btn btn-warning"
              - unless @current_user.needed_books.find_by_id(3).nil?
                label Book 3
                = form_for @current_user.needed_books.find_by_id(3), remote: true do |form|
                  .row
                    .col-5
                      = form.text_field :title, placeholder:"Book title", value:"#{@current_user.needed_books.find(3).title}", class:"form-control"
                    .col-5
                      = form.text_field :author, placeholder:"Book title", value:"#{@current_user.needed_books.find(3).author}", class:"form-control"
                    .col-2
                      = form.submit "Edit", class:"btn btn-warning"